### ISSUE TITLE
DNA methylation Data

### ISSUE THREAD

**Issue by pondandmoon** [JFchien/HumanBrainAging#1]
Hi,
I'm very interested in your work on how age and sex influence cell-type specificity of human cortical neurons. If possible, could you provide the count matrix for the single-cell methylation data? I would greatly appreciate access to this information.
Looking forward to your response.

**Comment by JFchien** [comment]
Hi,

Raw sequencing data and processed results from this study are available in
the GEO repository under accession number GEO: GSE247988
<https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE247988>

**Comment by pondandmoon** [comment]
Hi,
Thank you for your prompt reply. I apologize for not expressing myself clearly, which caused a misunderstanding. I've checked the data in the link [https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE247988](url)and found that only scRNA-seq data has a count matrix provided. I'd like to ask if you could provide the mCG and mCH DNA methylation matrices (i.e., matrices where rows represent genomic regions and columns represent cells).

**Comment by JFchien** [comment]
Hi, 
Since the dataset covers the whole genome, the methylation table at each C site for all cells would be extremely large. I recommend downloading the allc.tsv.gz files from the database, which contain the counts of methylated Cs and total Cs at each site. From there, you can extract the C sites in your regions of interest using allcools 
( [https://lhqing.github.io/ALLCools/command_line/allcools_extract.html](url) ) and then calculate the methylation levels.

**Comment by pondandmoon** [comment]
Hi,

Thank you for your detailed guidance. I will give it a try. 
Looking forward to your even more excellent work in the future.
